### ISSUE TITLE
Allotment.Pane should allow css classes / styles

### ISSUE THREAD

**Issue by theogravity** [johnwalley/allotment#107]
For example, I want to add an `overflow` attribute to one of the panes.

**Comment by johnwalley** [comment]
Hi @theogravity. That makes sense to me. If I add a className prop that will get merged with the existing class names on the top-level Pane element do you think that would suffice?

Just out of interest, do you have an example of where it's not possible to achieve what you want by styling the child of the Pane rather than the Pane itself?

**Comment by johnwalley** [comment]
I have a prototype up and running and it looks good.

![Dec-31-2021 15-42-46](https://user-images.githubusercontent.com/981531/147830979-5517d171-0246-4b0f-a5b9-9866e2019ee1.gif)

Here, the content of the left pane is fixed width and I've set the overflow of the Allotment.Pane to be `scroll`. The white background is the Pane content, and the red background is the Pane background.

The only reason I'm not merging it straight away is a small issue with the specificity of the rules. Basically, the Allotment.Pane classes are more specific than the single custom class you'd add yourself. Which means, any css would override your custom css. Once I've moved `overflow` off the Allotment.Pane component I don't see it being a problem but I'd like to do some testing first.

**Comment by johnwalley** [comment]
PR here: https://github.com/johnwalley/allotment/pull/108

**Comment by theogravity** [comment]
Wow, thank you for the prompt response and potential resolution. I'm working on an IDE of sorts that uses `memaid.js` to render charts. I'm using `allotment` to split the view into the editor and rendered sections.

https://github.com/theogravity/merman-ide/blob/main/packages/renderer/src/components/mermaid/MermaidContainer.tsx

The rendered portion emits an SVG, which relies on a well-defined width/height to properly render. There are circumstances where certain diagram types are larger than the renderer viewport, and allowing scroll would help readability.

<img width="799" alt="CleanShot 2021-12-31 at 20 48 02@2x" src="https://user-images.githubusercontent.com/855434/147844199-ec1094bd-7b37-4067-9199-d04ad46ff2c2.png">

<img width="800" alt="CleanShot 2021-12-31 at 20 48 59@2x" src="https://user-images.githubusercontent.com/855434/147844214-70c7b115-a0e5-4e56-bd69-1b6d48a59685.png">

I've tried to add various overflow attributes along with width/height, but could never get the scrollbars to appear unless it was on the parent (the pane).

https://github.com/theogravity/merman-ide/blob/main/packages/renderer/src/components/mermaid/MermaidRenderer.tsx

I had to hack it with the following css:

```
[data-testid="split-view-view"]:nth-child(2) {
    overflow: auto !important;
    background: white;
}
```

**Comment by johnwalley** [comment]
Thanks for the extra info. Looks good! It's funny seeing an Allotment component inside a Monaco editor component as I assume they share the same underlying split view implementation.

What __should__ work is adding an extra div which is the same size as the Pane and giving it the overflow value you want, e.g.

<img width="805" alt="Screenshot 2022-01-02 at 00 21 30" src="https://user-images.githubusercontent.com/981531/147862946-00ecf951-f5bf-4e43-b3b6-7fd215f3b8d6.png">

Which I __think_I is what we're after? But I could be wrong!

<img width="794" alt="Screenshot 2022-01-02 at 00 19 26" src="https://user-images.githubusercontent.com/981531/147862951-0c7badcd-11ea-4324-9e12-330d35de7de3.png">

The downside to this is that it's yet another div. The upside is that we don't need to modify the css for the Allotment components.

I'll probably go ahead and add the className prop to the Pane component regardless.

**Comment by johnwalley** [comment]
Forgot to test horizontal panes. Seems ok?

<img width="486" alt="Screenshot 2022-01-02 at 00 35 38" src="https://user-images.githubusercontent.com/981531/147863127-2f74d93b-2ef7-4c47-bed2-a92a2815c80c.png">

Although I note that running on macos in Chrome you can see that overflow 'auto' only displays scrollbars if the content overflows in the vertical direction. If it only overflows horizontally, then you can scroll but you don't see a scrollbar. Webdev 🤷‍♀️

**Comment by theogravity** [comment]
Looks reasonable, thanks!

**Comment by johnwalley** [comment]
I think this is done so I'm closing. Please let me know if this isn't the case.
