### ISSUE TITLE
Visible prop rerender issue

### ISSUE THREAD

**Issue by boyswan** [johnwalley/allotment#169]
Currently the visible prop is behaving strangely on initial mount - it seems it needs a rerender to take effect.

Examples
https://codesandbox.io/s/angry-swirles-c3d3ji?file=/src/App.js

**Comment by johnwalley** [comment]
Thanks @boyswan! I've merged a fix and released as [v1.9.1](https://github.com/johnwalley/allotment/releases/tag/v1.9.1).
