### ISSUE TITLE
AllotmentHandle  does not have resize function

### ISSUE THREAD

**Issue by waldjdida** [johnwalley/allotment#176]
The doc shows that we can use ref.current.resize([123,344]) however the AllotmentHandle  does not have resize function

export declare type AllotmentHandle = {
    reset: () => void;
};

Any help?

**Comment by johnwalley** [comment]
Could you just confirm which version of the library you've tested with?

**Comment by johnwalley** [comment]
I'm closing this as stale. Please ping me or create a new issue if this is still a problem.
