### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by mooijtech** [johnwalley/allotment#23]
Hello John,

I'm wanting to try allotment in a new React project but I'm getting the following:
```
SyntaxError: Cannot use import statement outside a module
```
At:
```
allotment (1:0) @ eval

> 1 | module.exports = require("allotment");
```

Any idea how to solve this issue?

Kind regards,
Marten Mooij

**Comment by mooijtech** [comment]
Hey John,

Sorry for my late reply.
What's the syntax you are using for the workaround?
The following doesn't seem to work for me:
```
import dynamic from "next/dynamic"

const Allotment = dynamic(
    () => import("allotment"),
    { ssr: false }
)
```

The error:
```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `ForwardRef(LoadableComponent)`.
```

**Comment by mooijtech** [comment]
Got it to work using:
```
const Allotment = dynamic(() => import("allotment").then(mod => mod.Allotment), { ssr: false });
```

**Comment by mooijtech** [comment]
Might be a good idea to add that code to the FAQ, the referenced documentation doesn't contain ```.then(mod => mod.Allotment)``` which is required to make it work as far as I can see.

Thanks for your help!

**Comment by johnwalley** [comment]
Good point. I tend to import the problematic component in its own file. You can then use the dynamic import on that local file. But your way avoids the extra file. I'll have a go at explaining all this in the README. Thanks again for you help.
