### ISSUE TITLE
Shrink contents of pane to pane size

### ISSUE THREAD

**Issue by mooijtech** [johnwalley/allotment#24]
Hello John,

See the following video, how do I shrink the contents of the pane to be the pane size?
I'm not quite sure the CSS I need to change.
I would appreciate your help.

https://user-images.githubusercontent.com/64754391/139579364-07ce60fa-8093-4004-8179-d50831eda5f4.mp4

Thanks,
Marten Mooij

**Comment by johnwalley** [comment]
Another good question!

The allotment component will surround each the content in each pane with a div. It gives this div a particular height, e.g. 143px. It's then up to you how you want to render your content. The simplest thing to do is to give your content a height of 100%. Then it will take up the full space allotment makes available.

In your example it looks like your content has a fixed size (I'd expect to see a vertical scrollbar if it were changing size as you scroll).

In the storybook examples the content gets a 100% height.

<img width="1207" alt="Screenshot 2021-10-31 at 21 44 09" src="https://user-images.githubusercontent.com/981531/139602217-d2bdac80-ab3a-480c-8a69-5a2e1d8db8a2.png">

If instead I give it a fixed height you end up with something like this.

<img width="1212" alt="Screenshot 2021-10-31 at 21 46 36" src="https://user-images.githubusercontent.com/981531/139602242-8a8a2c1b-e51d-4403-90f5-887013569459.png">

Let me know if setting the height of the content div to 100% helps. If not we can dig deeper.

Once we sort this out I'll make sure it's documented.

**Comment by mooijtech** [comment]
Hey John,

Probably could of fixed this myself if I put more effort into it. 
I thought I needed to change Allotment's CSS instead of my own. 
Thanks for your help I appreciate it.

I fixed it by using (Tailwind CSS) ```h-full``` and ```overflow-y-auto``` on my table.

Thanks again,
Marten Mooij

**Comment by johnwalley** [comment]
I'll add the information about the library not modifying your content, and that you should set your content height to 100% to the documentation.

Thanks again for your help.
