### ISSUE TITLE
Content should not be visible if `visible` pane prop is false?

### ISSUE THREAD

**Issue by johnwalley** [johnwalley/allotment#251]
Currently if `visible` is set to false then the size of the pane is set to 0. However, if the content is larger than the size, it will be visible. For example, the text "Drag view here to display' is visible in this screenshot.

<img width="886" alt="Screenshot 2022-04-20 at 22 22 49" src="https://user-images.githubusercontent.com/981531/164325559-5b6272b3-0ae1-42f1-9c60-9666f8d81bc1.png">

Technically, this could be the concern of the user and they should set a suitable overflow value. Also note, that this is not really about whether the pane is visible, if the content overflows the pane at any size it is an issue. In practice I wonder if it is more ergonomic for Allotment to set overflow hidden and remove the requirement to care about this?

**Comment by Kaishley** [comment]
Hi @johnwalley, when will this fix be released?

**Comment by johnwalley** [comment]
Thanks for the nudge. I've just published it as [v1.14.0](https://github.com/johnwalley/allotment/releases/tag/v1.14.0)
