### ISSUE TITLE
Npm package using old version 1.2.4 and not the new 1.13.0

### ISSUE THREAD

**Issue by DarrinGinderPost** [johnwalley/allotment#287]
Hello, We are currently using this package through npm within one of our projects. We are looking to update our packages within that codebase, but the version of @qwtel/allotment on npm is using the old 1.2.4 version. This is causing dependency issues because of the old version using react 17.0.2. Was wondering if the npm package could be updated to the latest one

**Comment by johnwalley** [comment]
Hi @DarrinGinderPost. I think @qwtel/allotment is a fork of my project. You'd have to get in touch with them to ask about updating the npm package.

You're welcome to see if the latest version of allotment meet your needs. However, I'm not familiar with what changes @qwtel have made to the library so cannot give any guidance.
