### ISSUE TITLE
Removing multiple panes during a rerender causes a runtime error

### ISSUE THREAD

**Issue by Gelio** [johnwalley/allotment#314]
Hey! Thanks for a great library, it's a pleasure to use!

I encountered a runtime exception when I removed multiple panes during a single rerender:

![image](https://user-images.githubusercontent.com/889383/171161492-35597e07-efa9-4f40-acf3-32a0a3baeb1c.png)

## Analysis

I believe the problematic piece of code is this loop that calls `removeView` for each removed pane:

https://github.com/johnwalley/allotment/blob/cd38c27b3ec03de79079e1b5cb0ef54e1f1ca080/src/allotment.tsx#L297-L303

I believe the problem is with the order of removal. If we have 3 panes (indices `[0, 1, 2]`) and remove panes with indices `1` and `2` during a single render, then this loop calls `removeView(1)` and then `removeView(2)`. The second call fails because after the first `removeView(1)` there are only 2 panes (with indices `[0, 1]`). If the order of operations was reversed and we removed panes from last to first, we would call `removeView(2)` first and then `removeView(1)`, which would work as expected.

## Workarouund

The workaround that I came up with is to remove one pane at a time in a very quick succession to give those `useEffect`s time to refresh the indices.

Instead of just

```ts
const onClick = () => {
  setExtraPanesCount(0);
};
```

I now use:

```ts
const onClick = () => {
  const removePane = () => {
    setExtraPanesCount((panes) => {
      if (panes > 1) {
        setTimeout(removePane, 0);
      }
      return panes - 1;
    });
  };

  removePane();
};
```

which works well.

it would be ideal if I could remove all the panes at once but that requires fixing this bug.

**Comment by johnwalley** [comment]
I've created a PR (#320) with a fix 🙂. I also have a PR (#321) I'm working on which adds end-to-end tests which should help catch this type of error in the future.

I'll get them merged and published sometime this week.

**Comment by Gelio** [comment]
Thanks for the effort, I appreciate that you came up with a fix so soon :+1: I'm looking forward to having the fix released, but there's no rush, so take your time
