### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by xeladotbe** [johnwalley/allotment#492]
first of all, thanks for this great library. The last release was on August 24th and on August 29th you merged the PR "useIsomorphicLayoutEffect", I would like to see a new release that includes the PR, would that be possible?

Thank you and regards,
Alex

**Comment by johnwalley** [comment]
Hi @xeladotbe. Thanks for the nudge. I've just published v1.17.1 which should include that change.

**Comment by xeladotbe** [comment]
Amazing, thank you
