### ISSUE TITLE
(Question) How to override resizer style

### ISSUE THREAD

**Issue by elithrade** [johnwalley/allotment#54]
Hi thanks for the awsome library, I want to override the colour split reiszer, is there any easy way to override the default greyish colour?

**Comment by johnwalley** [comment]
Hi @elithrade. Good question!

You can use [CSS variables](https://developer.mozilla.org/en-US/docs/Web/CSS/--*) to override some of the styling. The default greyish colour is set using `--separator-border`.

<img width="230" alt="Screenshot 2021-11-23 at 09 40 15" src="https://user-images.githubusercontent.com/981531/143001468-7bbbd914-ca04-4edb-bc30-573fbb5544a2.png">

You should be able to override it by giving it a value in any element above the Allotment component. Let me know if you run into any problems.

I will also document this in the README.

**Comment by elithrade** [comment]
Thanks for your quick reply, I got it working as you suggested. Thanks again for the awesome library.
