### ISSUE TITLE
Failed to ref to Allotment.Pane

### ISSUE THREAD

**Issue by huoyingyangjie** [johnwalley/allotment#582]
Is it by design or is it a bug?

**Comment by johnwalley** [comment]
Sounds like a bug. A ref to the underlying `div` is exposed:

<img width="429" alt="Screenshot 2023-04-26 at 22 15 11" src="https://user-images.githubusercontent.com/981531/234704570-8c09fa1f-58d9-48fb-84f4-d9c15c12716c.png">

Could you provide a reproduction so I can diagnose the issue?

**Comment by EFF** [comment]
Having the same issue here, `paneRef` is always undefined.

```tsx
const MyParentComponent = () => {
  const paneRef = useRef<HTMLDivElement>(null) // not working
  const myComponentRef = useRef(null) // obv works
  const allotmentRef = React.useRef<AllotmentHandle>(null) // works
  
  return (
   <Allotment
     onChange={(size) => { /* some handler */}}
     ref={allotmentRef} // this one works
     >
       <Allotment.Pane ref={paneRef}> /* always undefined */
           <MyComponent ref={myComponentRef} /> /* this is my workaround */
        </Allotment.Pane>
  )
}
```

Experienced the issue on `1.17.1` and `1.19.0`
Note that in my case this pane is relatively 3 `Allotment` deep

**Comment by johnwalley** [comment]
I just had a quick look at this. I'm having some success with a change like this: https://github.com/johnwalley/allotment/pull/632. But I'll need to determine in more depth if it's correct (and work out what the correct types are).
