### ISSUE TITLE
how to change sash animation time?

### ISSUE THREAD

**Issue by PremExtensi** [johnwalley/allotment#718]
I'd like to control the speed of the sash (blue separator) animation time. 
Basically to turn it off so it would show immediately on mouse over.

Is there any API to do that?
If not could you add it?

**Comment by johnwalley** [comment]
Hi @PremExtensi. I've added a new css variable: `--sash-hover-transition-duration` in #740.

I could also put the transition behind a `@media (prefers-reduced-motion)` css rule but that doesn't feel quite right as it's not technically motion.
