### ISSUE TITLE
Not possible to set an id attribute on allotment component

### ISSUE THREAD

**Issue by Maximuschka** [johnwalley/allotment#751]
Good day!

For the purpose of automated UI testing, I am looking for a way to set dedicated id attribute on the allotment component. Preferably, I'd set it directly on the React component like this:
```
<Allotment
  id={id}
  className={css}
  separator={false}
  onDragEnd={(sizes) => this.onDragEnd(sizes)}
  onChange={(sizes) => this.onChange(sizes)}>
  {...}
</Allotment>
```

to then receive the html attribute on the div with class `"split-view"` (most outer container).

- Am I missing the correct configuration option?
- What would be your recommended way to achieve this? I would prefer to not use jQuery.

Thanks and best regards,
Max

**Comment by johnwalley** [comment]
Good spot. I've created #752 which is a straightforward change so I'll publish a new release when I get a spare few minutes.

**Comment by johnwalley** [comment]
https://www.npmjs.com/package/allotment/v/1.19.5
