### ISSUE TITLE
Panes do not resize when providing the onReset event

### ISSUE THREAD

**Issue by riazus** [johnwalley/allotment#803]
First of all, thanks for this awesome library.

I encountered a problem when using the `onReset` callback: the current implementation doesn't use the default resizing mechanism for the panes. Instead, it only calls the `onReset` handler.

For example, if I want to add some logic, I must also provide logic for changing the sizes.

```
<Allotment onReset={() => {
    // ... some logic
    base.onReset();
  }}
/>
```

Probably, we could call the default resizing implementation regardless of the nullability of the `onReset` callback?

> src/allotment.tsx
```
if (onReset) {
  onReset();
} else {
  splitViewRef.current?.distributeViewSizes();

  for (let index = 0; index < views.current.length; index++) {
    resizeToPreferredSize(index);
  }
}
```

I'm open to feedback and suggestions.

**Comment by loki344** [comment]
Yup, can confirm this issue
